- name: create ANTs directories
  file:
    path: /opt/quarantine/ANTs/build
    state: directory

- name: clone ANTs
  git:
    repo: https://github.com/ANTsX/ANTs.git
    dest: /opt/quarantine/ANTs/src
    version: a7eca60da98b311869a9ff24f52c7b3c819aa76e #2021-06-24

- name: configure and install ANTs
  shell: cmake -DITK_BUILD_MINC_SUPPORT=ON -DBUILD_TESTING=OFF -DRUN_LONG_TESTS=OFF -DRUN_SHORT_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/opt/quarantine/ANTs -DSuperBuild_ANTS_USE_GIT_PROTOCOL=OFF ../src && make -j {{ ansible_processor_vcpus }} && cd ANTS-build && make install
  args:
    chdir: /opt/quarantine/ANTs/build
    creates: /opt/quarantine/ANTs/bin

- name: add ANTs to path
  lineinfile:
    path: /etc/profile.d/99ANTs.sh
    line: "export PATH=/opt/quarantine/ANTs/bin${PATH:+:$PATH}"
    create: yes

- name: Install antspyx dependencies
  shell: /opt/quarantine/miniforge/bin/conda install --yes chart-studio webcolors
  when:
    - '"python" in ansible_run_tags or "all" in ansible_run_tags'

- name: Install antspyx
  pip:
    name: antspyx
    executable: /opt/quarantine/miniforge/bin/pip
  when:
    - '"python" in ansible_run_tags or "all" in ansible_run_tags'
